### ISSUE TITLE
wiki

### ISSUE THREAD

**Issue by CPernet** [LIMO-EEG-Toolbox/limo_meeg#1]
how to update STUDY for groups in command line? 
update https://github.com/LIMO-EEG-Toolbox/limo_meeg/wiki/Between-Subjects-Categorical-Designs

**Comment by arnodelorme** [comment]
I have added it. However, the GUI does not correspond to the numbering in the GUI. For the command line (which I just copied from the history by the way), I have copied the GUI.

**Comment by CPernet** [comment]
yep changed some bits (index of study = sub- indexing +1) 
thx
