### ISSUE TITLE
open LIMO eeg from the Study menu of EEGLAB

### ISSUE THREAD

**Issue by nargesnaghibi** [LIMO-EEG-Toolbox/limo_meeg#2]
Dear Dr. Pernet

I'm using LIMO EEG 2.0 and EEGLAB v2020.0. I can't access LIMO from the Study menu. Which version of eeglab should I switch to in order to access tools for estimation of model parameters of STUDYsets?

Thanks in advance,
Narges

**Comment by CPernet** [comment]
try the develop branch in https://github.com/sccn/eeglab -
