### ISSUE TITLE
limo_cluster_test

### ISSUE THREAD

**Issue by amisepa** [LIMO-EEG-Toolbox/limo_meeg#3]
Hi,

I was able to look at my results with both cluster- and TFCE- correction last week for main_effects, contrast1, contrast2, contrast3, and contrast4 with no problem (on ERP OLS model with 3 conditions). 
But I try to look at the results again today and receive this error:
![image](https://user-images.githubusercontent.com/58382227/108100224-7e0b0e80-703a-11eb-9d9d-1981bc086d34.png)
As if the file disappeared.

I can see files in H0 but not that specific file, not sure why it wouldn't be in there anymore. I am pretty sure I didn't delete anything in that folder.

Is this error normal or did I do something wrong? Now I need to reprocess 2nd level again?

Thanks,
Cedric

**Comment by CPernet** [comment]
update your path, this is in a subfolder (STUDY  does this for you)
