### ISSUE TITLE
LIMO file structure incomplete and files mismatched in pipeline.import

### ISSUE THREAD

**Issue by ChristineLackner** [LIMO-EEG-Toolbox/limo_meeg#5]
Good afternoon. Having some troubles with modeling (eventually at the second level) a 2 (faces) x 2 response (correct/error) x 3 (group) ANOVA on ERNs. I'd appreciate some help with the following:
In the first level analysis, a limo_pipeline.mat file is created. In it, under the pipeline.import variable, files_in and files_out do not match. They will have very different subjects in them. 
![image](https://user-images.githubusercontent.com/84984735/120013846-ae5a3580-bfb7-11eb-8f1a-f00a69098801.png)

However, the pipeline.design files do appear to match... 
![image](https://user-images.githubusercontent.com/84984735/120013873-b4501680-bfb7-11eb-97d3-8df1f7370ece.png)

This seems to result in not creating the subfolders for each participant. For instance, derivatives/sub-019/eeg will have a Faces_GLM_Channels_Time_WLS subfolder, but derivatives/sub-019/eeg will have no such subfolder.
Sub-019 will have all of the Beta Weights, cons, R's, Y's created (presumably for the wrong participant as they don't line up in limo_pipeline), but sub-020 will not.

I have checked that there is nothing wrong with sub-020's data. 

In order to help you understand my problem more deeply, here are a few relevant screenshots:
Two example study design pages (there are 300 .set files in the study – 75 partic x 4 conditions)
![image](https://user-images.githubusercontent.com/84984735/120013904-bfa34200-bfb7-11eb-9387-dfd4206c360e.png)

Here is the study design I'm using for the first level analysis – the four conditions. Two faces – Happy and Fearful x 2 types of responses – correct and incorrect
![image](https://user-images.githubusercontent.com/84984735/120013920-c9c54080-bfb7-11eb-8ac3-84b5e1a9b064.png)

Here is the GUI for the first step... 
![image](https://user-images.githubusercontent.com/84984735/120013932-cd58c780-bfb7-11eb-9a4c-67d28f29b7ad.png)

The PIPE history report for the uncompleted subjects doesn't seem to show much... it says completed, when it doesn't appear to be that way at all as the correct folder structure hasn't been created and I still have the problem of the limo_pipeline files not matching up properly.

![image](https://user-images.githubusercontent.com/84984735/120013943-d21d7b80-bfb7-11eb-8e67-dd6a09c953b1.png)

**Comment by CPernet** [comment]
yes we have seen this issue - due to some errors in EEGLAB interface -- do try the dev. version https://github.com/sccn/eeglab/tree/develop in which I pushed all the changes handling this - thx 
ping @arnodelorme those changes need to make there way in a stable release ...

**Comment by ChristineLackner** [comment]
Thanks Dr. Pernet for that. I cloned the development version and now I am running into a new error while running the first level analysis...  error occurred in function std_limo at line 313.
Opening std_limo and looking at line 313 suggests that it has something to do with the "session" information. I have double checked that the session numbers (all session 1) are there in the study design. Any further advice?

**Comment by CPernet** [comment]
sure - share with me a few subjects and your study file and I'll fix it

**Comment by ChristineLackner** [comment]
OneDrive link

https://msvuhfx-my.sharepoint.com/:f:/g/personal/christine_lackner_msvu_ca/EggBomiuAI9MlXvYUG3DiToBZY7MOrsN8ZWhmRC5rjHJJg?email=wamcyril%40gmail.com&e=jE5RpE

wamcyril@gmail.com

**Comment by CPernet** [comment]
would you mind copy/paste the error from the command thx

**Comment by arnodelorme** [comment]
Dear Christine,

Would you mind to upload the whole dataset. We cannot test with the reduced version.
Best wishes,

**Comment by CPernet** [comment]
or simpler if you resave your study with just the few subjects you shared -- thx you

**Comment by CPernet** [comment]
Hi Christine, the issue stems from the fact that you used conditions -- a single .set file with all 4 conditions is needed see the tiorial here https://github.com/LIMO-EEG-Toolbox/limo_meeg/wiki/1.-Preprocessing - do let us know how this goes

**Comment by arnodelorme** [comment]
Hi Christine, we have looked in detail at the issue. There is a current limitation of LIMO that you cannot process multiple datasets when you have one per condition.
1. Merge all datasets for the same subjects
2. You will need first to add the information of the type of stimulus to time locking events

Future versions of LIMO will be able to process your STUDY as is, but we cannot promises a date. Could be in a month or in a year.

**Comment by ChristineLackner** [comment]
THANK YOU!!! I will try this.
