### ISSUE TITLE
Matlab v2016b error in exist function; 'File' is not accepted as an argument

### ISSUE THREAD

**Issue by jnvandermeer** [LIMO-EEG-Toolbox/limo_meeg#7]
I realize this probably needs to go into the bids-matlab-tools repo, but I encountered this while running your tutorial:

![image](https://user-images.githubusercontent.com/2698152/159674760-adf287b8-2335-483a-8cc1-706bb07402da.png)

My matlab version R2016b might be too old. Could you update in the installation which version of Matlab you recommend?

**Comment by CPernet** [comment]
pop_import is an EEGLAB function, not sure I can help here - best to post on the EEGLAB list
