### ISSUE TITLE
Issue with Limo

### ISSUE THREAD

**Issue by ArianaLopes27** [LIMO-EEG-Toolbox/limo_meeg#8]
Good afternoon,
I am having problems using LIMO, specifically because every time I run the first-level analysis, I get the information that design and glm were not able to execute, as seen in the following picture. In the end of this step, the following error is sent also "Invalid file identifier. Use fopen to generate a valid file identifier".

<img width="1167" alt="Captura de ecrã 2023-04-22, às 16 55 23" src="https://user-images.githubusercontent.com/131543323/233794431-348341d0-a098-4cef-8509-2add794df747.png">

After that, when I start the second level analysis, my study does not have the BETA files that are supposed to be created earlier to use in this step. What can I do to solve this problem?

**Comment by CPernet** [comment]
sorry, i missed your message - do you still need help?
